FROM node:12.16.3-alpine3.11

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --silent

# Bundle app source
COPY . .

EXPOSE 3002

CMD ["npm", "start"]